# Generated by Django 5.0.3 on 2024-03-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Felino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200)),
                ('portuguese_name', models.CharField(max_length=200)),
                ('english_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=250)),
                ('image_name', models.CharField(max_length=200)),
                ('habitat', models.CharField(max_length=200)),
                ('curiosities', models.TextField()),
            ],
        ),
    ]
